#!/usr/bin/env node
/**
 * feature-index.ts — Cheap, auto-generated roll-up of every feature folder.
 *
 * PROBLEM (PRIORITY 2 — architecture scaling): as the number of features under
 * docs/specs/ grows, resume/overview logic that scans every directory and parses
 * each per-feature context-summary.md becomes expensive to load into a session.
 * INDEX.md is a single, small, flat table that the workflow can read instead of
 * fanning out across folders.
 *
 * SOURCE OF TRUTH: the per-feature context-summary.md (its Raw JSON block) and
 * eval-baseline.json. This file DUPLICATES NO TRUTH — it only projects fields
 * that already exist in those artifacts. Delete INDEX.md and it regenerates
 * identically. If a folder has no context-summary.md it is not a workflow feature
 * folder (e.g. a raw-spec-only directory) and is skipped.
 *
 * Usage:
 *   npx tsx .claude/integrations/feature-index.ts            # regenerate docs/specs/INDEX.md
 *   npx tsx .claude/integrations/feature-index.ts --check    # exit 1 if INDEX.md is stale (CI/posttest)
 *   npx tsx .claude/integrations/feature-index.ts --json     # print rows as JSON (cheap resume read)
 */

import * as fs from 'fs';
import * as path from 'path';

const SPECS_DIR = path.join('docs', 'specs');
const INDEX_PATH = path.join(SPECS_DIR, 'INDEX.md');

export interface FeatureRow {
  feature: string;
  phase: string;
  taskType: string;
  evalScore: string;       // e.g. "94" or "95%" or "—"
  finalConfirmed: boolean;
  lastUpdated: string;     // ISO string or ""
}

/** Extract the Raw JSON block from a context-summary.md, or null. */
export function parseContextJson(content: string): Record<string, unknown> | null {
  // Tolerate CRLF — older committed context-summary.md files use \r\n.
  const match = content.match(/```json\r?\n([\s\S]+?)\r?\n```/);
  if (!match) return null;
  try {
    return JSON.parse(match[1]) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/** Resolve the eval score for a feature, preferring the machine-written baseline. */
function resolveEvalScore(featureDir: string, ctx: Record<string, unknown>): string {
  const baselinePath = path.join(featureDir, 'eval-baseline.json');
  if (fs.existsSync(baselinePath)) {
    try {
      const baseline = JSON.parse(fs.readFileSync(baselinePath, 'utf-8'));
      if (typeof baseline.overall === 'number') return String(baseline.overall);
    } catch {
      /* fall through to context value */
    }
  }
  if (typeof ctx.evalOverall === 'string' && ctx.evalOverall) return ctx.evalOverall;
  return '—';
}

/**
 * Scan a specs directory and project one row per *feature folder* (a subdirectory
 * that contains a context-summary.md). Dot-directories (.amendments, etc.) and
 * spec-only folders are skipped.
 */
export function collectFeatures(specsDir: string): FeatureRow[] {
  if (!fs.existsSync(specsDir)) return [];
  const rows: FeatureRow[] = [];

  for (const entry of fs.readdirSync(specsDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
    const featureDir = path.join(specsDir, entry.name);
    const ctxPath = path.join(featureDir, 'context-summary.md');
    if (!fs.existsSync(ctxPath)) continue; // not a workflow feature folder

    const ctx = parseContextJson(fs.readFileSync(ctxPath, 'utf-8'));
    if (!ctx) continue;

    const phase = typeof ctx.phase === 'string' ? ctx.phase : '';
    const finalConfirmed = ctx.finalConfirmed === true || phase === 'final_confirmed';

    rows.push({
      feature: typeof ctx.featureName === 'string' ? ctx.featureName : entry.name,
      phase: phase || '—',
      taskType: typeof ctx.taskType === 'string' && ctx.taskType ? ctx.taskType : '—',
      evalScore: resolveEvalScore(featureDir, ctx),
      finalConfirmed,
      lastUpdated: typeof ctx.updatedAt === 'string' ? ctx.updatedAt : '',
    });
  }

  // Most-recently-touched first — the row a resume is most likely to want.
  rows.sort((a, b) => b.lastUpdated.localeCompare(a.lastUpdated));
  return rows;
}

/** Render the flat INDEX.md table. Deterministic: same rows → identical bytes. */
export function renderIndex(rows: FeatureRow[]): string {
  const header = [
    '# Feature Index',
    '',
    '> Auto-generated by `.claude/integrations/feature-index.ts`. Do NOT edit manually.',
    '> Source of truth: each feature\'s `context-summary.md` (Raw JSON) + `eval-baseline.json`.',
    '> Regenerate: `npm run workflow:index`. Verify in sync: `npm run workflow:index -- --check`.',
    '',
  ];

  if (rows.length === 0) {
    return [...header, '_No feature folders found._', ''].join('\n');
  }

  const lines = [
    ...header,
    `**${rows.length}** feature folder(s) · ${rows.filter((r) => r.finalConfirmed).length} final-confirmed.`,
    '',
    '| Feature | Phase | Task type | Eval | Final | Last updated |',
    '|---------|-------|-----------|------|-------|--------------|',
    ...rows.map((r) => {
      const date = r.lastUpdated ? r.lastUpdated.slice(0, 10) : '—';
      const fin = r.finalConfirmed ? '✅' : '—';
      return `| ${r.feature} | ${r.phase} | ${r.taskType} | ${r.evalScore} | ${fin} | ${date} |`;
    }),
    '',
  ];
  return lines.join('\n');
}

/**
 * True iff INDEX.md is in sync with the freshly-rendered content, ignoring line-ending
 * differences only. The writer always emits LF (`renderIndex` join('\n')), but an autocrlf
 * checkout materializes the working-tree INDEX.md as CRLF, so a raw byte compare falsely reports
 * "stale" on every Windows checkout (E-02). Normalizing CRLF→LF on BOTH operands makes `--check`
 * EOL-agnostic while still catching genuine content drift (only the \r\n axis is collapsed).
 */
export function indexInSync(actual: string, expected: string): boolean {
  const normEol = (s: string) => s.replace(/\r\n/g, '\n');
  return normEol(actual) === normEol(expected);
}

/** Regenerate INDEX.md from the live specs dir. Returns the rendered content. */
export function regenerateIndex(specsDir: string = SPECS_DIR, indexPath: string = INDEX_PATH): string {
  const rows = collectFeatures(specsDir);
  const content = renderIndex(rows);
  fs.mkdirSync(path.dirname(indexPath), { recursive: true });
  fs.writeFileSync(indexPath, content, 'utf-8');
  return content;
}

// ─── CLI ─────────────────────────────────────────────────────────────────────

if (process.argv[1] && process.argv[1].includes('feature-index') && !process.argv[1].includes('.test.')) {
  const args = process.argv.slice(2);

  if (args.includes('--json')) {
    console.log(JSON.stringify(collectFeatures(SPECS_DIR), null, 2));
  } else if (args.includes('--check')) {
    const rows = collectFeatures(SPECS_DIR);
    const expected = renderIndex(rows);
    const actual = fs.existsSync(INDEX_PATH) ? fs.readFileSync(INDEX_PATH, 'utf-8') : '';
    if (!indexInSync(actual, expected)) {
      console.error('❌ docs/specs/INDEX.md is stale. Run: npm run workflow:index');
      process.exit(1);
    }
    console.log(`✅ INDEX.md in sync (${rows.length} feature folder(s)).`);
  } else {
    const content = regenerateIndex();
    const count = collectFeatures(SPECS_DIR).length;
    console.log(`✅ Wrote ${INDEX_PATH} (${count} feature folder(s), ${content.length} bytes).`);
  }
}
