/**
 * memory.ts — Context persistence for /feature-from-confluence
 *
 * Implements the ★5 CONTEXT SUMMARY behavior from AGENT_SPEC.md.
 * Follows claude-mem patterns: https://github.com/thedotmack/claude-mem
 *
 * Usage (invoked by the command at each confirm gate):
 *   npx tsx .claude/integrations/memory.ts save <phase> <json-payload>
 *   npx tsx .claude/integrations/memory.ts load
 *   npx tsx .claude/integrations/memory.ts clear
 *
 * Examples:
 *   npx tsx .claude/integrations/memory.ts save scope_confirmed '{"featureName":"UserProfile","taskType":"NEW"}'
 *   npx tsx .claude/integrations/memory.ts load
 *   npx tsx .claude/integrations/memory.ts clear
 *
 * Option B folder structure: docs/specs/<FeatureName>/context-summary.md
 * Pointer file: docs/specs/.current-feature  (tracks which feature is active)
 */

import * as fs from 'fs';
import * as path from 'path';
import { regenerateIndex, parseContextJson } from './feature-index';
import { generateDigest } from './feature-digest';

const SPECS_DIR = path.join('docs', 'specs');
const CURRENT_FEATURE_PATH = path.join(SPECS_DIR, '.current-feature');

// Measurement-layer v1 (measurement-layer-v1.md §3.2, §4 trusted-writer invariant):
// the verify verdict is NEVER writable via the general `save` path. `verified`/
// `testsPassed`/`verify_complete` may only be set by the capture wrapper
// (record-verify.ts recordVerify), which computes them from a real test-runner exit
// code it observed directly. The general save path is narrative-only, so an external
// caller cannot assert its own verification verdict. Refusal is key-based (not merely
// phase-scoped) because saveContext merges prior payloads forward — a verdict key
// sneaked in at an earlier phase would otherwise persist into verify_complete.
const FORBIDDEN_VERIFY_KEYS = ['testsPassed', 'verified', 'verify_complete'] as const;

interface ContextSummary {
  phase: string;
  featureName: string;
  taskType: 'NEW' | 'BASELINE' | 'LEGACY' | '';
  userAnswers: Record<string, unknown>;
  skippedSteps: Array<{ step: string; reason: string }>;
  pendingSteps: string[];
  decisions: Record<string, string>;
  finalConfirmed?: boolean;
  confirmedAt: string;
  updatedAt: string;
}

function ensureDir(filePath: string): void {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
}

export function getCurrentFeatureName(): string | null {
  if (!fs.existsSync(CURRENT_FEATURE_PATH)) return null;
  const name = fs.readFileSync(CURRENT_FEATURE_PATH, 'utf-8').trim();
  return name || null;
}

function setCurrentFeatureName(name: string): void {
  ensureDir(CURRENT_FEATURE_PATH);
  fs.writeFileSync(CURRENT_FEATURE_PATH, name, 'utf-8');
}

export function getContextPath(featureName: string): string {
  return path.join(SPECS_DIR, featureName, 'context-summary.md');
}

export function loadContext(): ContextSummary | null {
  const featureName = getCurrentFeatureName();
  if (!featureName) return null;

  const contextPath = getContextPath(featureName);
  if (!fs.existsSync(contextPath)) return null;

  // Parse via the shared CRLF-tolerant parser in feature-index (single source of
  // truth — git autocrlf rewrites this file's LF to \r\n on checkout, which an
  // LF-only regex would fail to parse). See feature-index.parseContextJson.
  const data = parseContextJson(fs.readFileSync(contextPath, 'utf-8'));
  return data ? (data as unknown as ContextSummary) : null;
}

export function saveContext(phase: string, payload: Partial<ContextSummary>): void {
  const featureName = payload.featureName ?? getCurrentFeatureName() ?? '';
  if (!featureName) {
    console.error('Error: featureName must be present in JSON payload for the first save call.');
    console.error('Example: { "featureName": "UserProfile", "taskType": "NEW", ... }');
    process.exit(1);
  }

  // Update the current-feature pointer
  setCurrentFeatureName(featureName);

  const contextPath = getContextPath(featureName);

  // Load existing context from this feature's folder (if any)
  let existing: ContextSummary | null = null;
  if (fs.existsSync(contextPath)) {
    const data = parseContextJson(fs.readFileSync(contextPath, 'utf-8'));
    if (data) existing = data as unknown as ContextSummary;
  }

  const base: ContextSummary = existing ?? {
    phase: '',
    featureName,
    taskType: '' as const,
    userAnswers: {},
    skippedSteps: [],
    pendingSteps: [],
    decisions: {},
    confirmedAt: '',
    updatedAt: '',
  };

  const updated: ContextSummary = {
    ...base,
    ...payload,
    phase,
    featureName,
    updatedAt: new Date().toISOString(),
    confirmedAt: new Date().toISOString(),
  };

  const markdown = `# Context Summary — /feature-from-confluence

> Auto-generated by .claude/integrations/memory.ts
> Load this file at session start to resume from last confirmed step.
> Do NOT edit manually.

## Current Phase

**${updated.phase}** — last confirmed at ${updated.confirmedAt}

## Summary

- **Feature**: ${updated.featureName || '(not yet set)'}
- **Task type**: ${updated.taskType || '(not yet detected)'}
- **Final confirmed**: ${updated.finalConfirmed ? 'YES ✅' : 'No'}

## Skipped Steps

${
  updated.skippedSteps.length > 0
    ? updated.skippedSteps.map((s) => `- **${s.step}**: ${s.reason}`).join('\n')
    : '_None_'
}

## Pending Steps

${updated.pendingSteps.length > 0 ? updated.pendingSteps.map((s) => `- ${s}`).join('\n') : '_None_'}

## Raw JSON

\`\`\`json
${JSON.stringify(updated, null, 2)}
\`\`\`
`;

  ensureDir(contextPath);
  fs.writeFileSync(contextPath, markdown, 'utf-8');
  console.log(`✅ Context saved: phase=${phase} → ${contextPath}`);

  // Keep the cross-feature roll-up fresh. INDEX.md is a pure projection of the
  // context-summary.md files (no duplicated truth) — cheap to regenerate here so
  // resume/overview reads never have to fan out across every feature folder.
  try {
    regenerateIndex();
  } catch (e) {
    console.error(`⚠️  INDEX.md refresh skipped: ${(e as Error).message}`);
  }

  // On final confirmation, emit the compact resume digest for this feature.
  // Derived state only — safe to fail; the raw artifacts remain the source of truth.
  if (updated.finalConfirmed) {
    try {
      const res = generateDigest(featureName);
      if (res.written) console.log(`📄 Feature digest written: ${res.digestPath}`);
    } catch (e) {
      console.error(`⚠️  Digest generation skipped: ${(e as Error).message}`);
    }
  }
}

export function clearContext(): void {
  const featureName = getCurrentFeatureName();
  if (!featureName) {
    console.log('No active feature context to clear.');
    return;
  }

  const contextPath = getContextPath(featureName);
  if (fs.existsSync(contextPath)) {
    fs.unlinkSync(contextPath);
    console.log(`🗑️ Context cleared: ${contextPath}`);
  } else {
    console.log(`No context file found for feature "${featureName}".`);
  }

  // Clear the pointer
  if (fs.existsSync(CURRENT_FEATURE_PATH)) {
    fs.unlinkSync(CURRENT_FEATURE_PATH);
    console.log(`🗑️ Pointer cleared: ${CURRENT_FEATURE_PATH}`);
  }
}

function printContext(ctx: ContextSummary | null): void {
  if (!ctx) {
    console.log('No context found. This is a fresh session.');
    return;
  }
  console.log('\n=== Loaded Context ===');
  console.log(`Phase         : ${ctx.phase}`);
  console.log(`Feature       : ${ctx.featureName}`);
  console.log(`Task type     : ${ctx.taskType}`);
  console.log(`Final confirm : ${ctx.finalConfirmed ? 'YES' : 'No'}`);
  console.log(`Last updated  : ${ctx.updatedAt}`);
  console.log(`Skipped steps : ${ctx.skippedSteps.map((s) => s.step).join(', ') || 'none'}`);
  console.log('\n--- JSON ---');
  console.log(JSON.stringify(ctx, null, 2));
}

// Entry point — guarded so importing this module (e.g. from memory.test.ts) does
// not execute the CLI. Mirrors the guard pattern in check-ownership.ts / regression-corpus.ts.
function main(): void {
  const [, , command, ...rest] = process.argv;

  switch (command) {
  case 'save': {
    const phase = rest[0];
    const payloadStr = rest[1] ?? '{}';
    if (!phase) {
      console.error('Usage: memory.ts save <phase> [json-payload]');
      process.exit(1);
    }
    let payload: Partial<ContextSummary> = {};
    try {
      payload = JSON.parse(payloadStr);
    } catch {
      console.error('Invalid JSON payload:', payloadStr);
      process.exit(1);
    }
    // Trusted-writer invariant (measurement-layer-v1.md §3.2/§4): refuse any
    // externally-supplied verify verdict. The verdict is computed by the capture
    // wrapper from a real exit code, never accepted here as input.
    const smuggled = FORBIDDEN_VERIFY_KEYS.filter((k) =>
      Object.prototype.hasOwnProperty.call(payload, k)
    );
    if (smuggled.length > 0) {
      console.error(
        `❌ Refused: the verify verdict cannot be set via 'save' (forbidden key(s): ${smuggled.join(', ')}).`
      );
      console.error(
        "   `verified`/`testsPassed`/`verify_complete` are computed by the capture wrapper"
      );
      console.error(
        '   (record-verify.ts) from a real test-runner exit code — never self-reported.'
      );
      console.error('   Narrative saves (featureName, notes, decisions, …) are still allowed.');
      process.exit(1);
    }
    saveContext(phase, payload);
    break;
  }

  case 'load': {
    const ctx = loadContext();
    printContext(ctx);
    break;
  }

  case 'clear': {
    clearContext();
    break;
  }

  default: {
    console.log(`
Usage:
  npx tsx .claude/integrations/memory.ts save <phase> [json-payload]
  npx tsx .claude/integrations/memory.ts load
  npx tsx .claude/integrations/memory.ts clear

Phases (from AGENT_SPEC B0–B12):
  task_type_detected | scope_confirmed | files_confirmed | plan_confirmed | final_confirmed

Note: featureName must be in the JSON payload on first save.
Context is stored at: docs/specs/<featureName>/context-summary.md
Active feature tracked at: docs/specs/.current-feature
`);
  }
  }
}

if (process.argv[1] && /memory\.ts$/.test(process.argv[1].replace(/\\/g, '/'))) {
  main();
}
