/** Offline P2-B runtime evidence. All role executions/merges are injected fakes; no process is launched. */
import * as assert from 'assert';
import { executeValidatedRolePlan, type RoleExecutionRequest } from './multi-agent-runtime';
import type { AgentHandoff, EvidenceVerifier, RoleDag } from './multi-agent-orchestration';
let passed = 0; let failed = 0;
async function test(name: string, fn: () => void | Promise<void>) { try { await fn(); passed++; console.log(`✅ ${name}`); } catch (error) { failed++; console.error(`❌ ${name}\n${(error as Error).stack ?? error}`); } }
const HASH = 'c'.repeat(64); const evidence: EvidenceVerifier = { verify: () => ({ valid: true }) };
const plan = (tasks: RoleDag['tasks']): RoleDag => ({ contractHash: HASH, tasks });
const contexts = (dag: RoleDag) => dag.tasks.map((task) => ({ taskId: task.id, prompt: `role ${task.role}`, contextTokens: 10 }));
function handoff(request: RoleExecutionRequest, overrides: Partial<AgentHandoff> = {}): AgentHandoff { return { taskId: request.task.id, role: request.task.role, agentId: request.lease.ownerId, leaseId: request.lease.leaseId, featureName: 'Feature', phase: request.task.evidencePhase, contractHash: HASH, contextTokens: request.context.contextTokens, passClaim: true, requireBackendBinding: false, ...overrides }; }
function input(dag: RoleDag, execute: (request: RoleExecutionRequest) => Promise<unknown>, extras: Record<string, unknown> = {}) { return { dag, featureName: 'Feature', contexts: contexts(dag), evidenceVerifier: evidence, executor: { execute }, merger: { merge: async () => 'merged output' }, finalGate: async (output: string) => ({ passed: output === 'merged output', detail: 'same gate' }), clock: { nowMs: () => 100 }, leaseIds: { next: (taskId: string, attempt: number) => `${taskId}-${attempt}` }, deadline: { race: async ({ promise }: { promise: Promise<unknown> }) => ({ timedOut: false, value: await promise }) }, maxAttemptsPerTask: 2, ...extras }; }
async function main() {
 await test('dependency-ready roles execute in one parallel non-shell wave with isolated contexts and verified predecessor bundle refs', async () => { const dag = plan([{ id:'design',role:'design',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100 },{ id:'ui',role:'ui',dependsOn:['design'],evidencePhase:'B2',contextBudgetTokens:20,timeoutMs:100 },{ id:'dev',role:'dev',dependsOn:[],evidencePhase:'B3',contextBudgetTokens:20,timeoutMs:100 }]); const calls: RoleExecutionRequest[]=[]; const result=await executeValidatedRolePlan(input(dag, async r=>{ calls.push(r); return {status:'handoff',handoff:handoff(r)}; })); assert.equal(result.passed,true); assert.equal(calls[0].shell,false); assert.equal(calls[1].shell,false); assert.equal(calls.filter(c=>c.task.id==='ui')[0].predecessorBundles[0].taskId,'design'); assert.equal(calls.filter(c=>c.task.id==='ui')[0].context.taskId,'ui'); });
 await test('forged handoff evidence stops execution before merge or final gate', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]); let merges=0,gates=0; const result=await executeValidatedRolePlan(input(dag,async r=>({status:'handoff',handoff:handoff(r)}),{evidenceVerifier:{verify:()=>({valid:false})},merger:{merge:async()=>{merges++;return 'x'}},finalGate:async()=>{gates++;return {passed:true,detail:'x'}}})); assert.equal(result.reason,'handoff-rejected');assert.equal(merges,0);assert.equal(gates,0); });
 await test('timeout explicitly reclaims its lease and retries once, while exhausted timeout fails closed', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]);let calls=0;const ok=await executeValidatedRolePlan(input(dag,async r=>{calls++;return calls===1?{status:'timeout'}:{status:'handoff',handoff:handoff(r)}}));assert.equal(ok.passed,true);assert.equal(calls,2);const exhausted=await executeValidatedRolePlan(input(dag,async()=>({status:'timeout'}),{maxAttemptsPerTask:1}));assert.equal(exhausted.reason,'timeout-exhausted'); });
 await test('context starvation and cross-agent contract drift stop before merge', async () => { const dag=plan([{id:'ui',role:'ui',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:10,timeoutMs:100}]);let calls=0;const starved=await executeValidatedRolePlan(input(dag,async r=>{calls++;return {status:'handoff',handoff:handoff(r)}},{contexts:[{taskId:'ui',prompt:'x',contextTokens:11}]}));assert.equal(starved.reason,'context-starved');assert.equal(calls,0);const drift=await executeValidatedRolePlan(input(dag,async r=>({status:'handoff',handoff:handoff(r,{contractHash:'d'.repeat(64)})})));assert.equal(drift.reason,'handoff-rejected'); });
 await test('an executor exception is fail-closed and does not reach merger or gate', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]);let merges=0;const result=await executeValidatedRolePlan(input(dag,async()=>{throw new Error('fixture')},{merger:{merge:async()=>{merges++;return 'x'}}}));assert.equal(result.reason,'executor-error');assert.equal(merges,0); });
 await test('runtime deadline turns a never-resolving executor into timeout exhaustion and ignores late completion', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]);let resolve!: (value: unknown)=>void;const hanging=new Promise<unknown>(r=>{resolve=r});const result=await executeValidatedRolePlan(input(dag,async()=>hanging,{maxAttemptsPerTask:1,deadline:{race:async()=>({timedOut:true})}}));assert.equal(result.reason,'timeout-exhausted');resolve({status:'handoff'});assert.equal(result.handoffs.length,0); });
 await test('executor receives frozen snapshots and cannot mutate the DAG, context, or lease used for merge', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]);const original=dag.tasks[0].id;const result=await executeValidatedRolePlan(input(dag,async r=>{try{(r.task as {id:string}).id='evil'}catch{}try{(r.task.dependsOn as string[]).push('evil')}catch{}try{(r.context as {prompt:string}).prompt='evil'}catch{}try{(r.lease as {leaseId:string}).leaseId='evil'}catch{}assert.equal(r.task.id,'dev');assert.deepEqual(r.task.dependsOn,[]);assert.equal(r.context.prompt,'role dev');assert.equal(r.lease.leaseId,'dev-1');return {status:'handoff',handoff:handoff(r)};}));assert.equal(result.passed,true);assert.equal(dag.tasks[0].id,original); });
 await test('throwing clock and lease-id sources fail closed rather than crashing', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]);const clockFail=await executeValidatedRolePlan(input(dag,async r=>({status:'handoff',handoff:handoff(r)}),{clock:{nowMs:()=>{throw new Error('clock')}}}));assert.equal(clockFail.reason,'clock-error');const leaseFail=await executeValidatedRolePlan(input(dag,async r=>({status:'handoff',handoff:handoff(r)}),{leaseIds:{next:()=>{throw new Error('lease')}}}));assert.equal(leaseFail.reason,'lease-id-error'); });
 await test('merge is unreachable before all bundles and the same final gate rejects plausible wrong output', async () => { const dag=plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100},{id:'ui',role:'ui',dependsOn:[],evidencePhase:'B2',contextBudgetTokens:20,timeoutMs:100}]);let merges=0;const incomplete=await executeValidatedRolePlan(input(dag,async r=>r.task.id==='ui'?{status:'timeout'}:{status:'handoff',handoff:handoff(r)},{maxAttemptsPerTask:1,merger:{merge:async()=>{merges++;return 'x'}}}));assert.equal(incomplete.reason,'timeout-exhausted');assert.equal(merges,0);const gateFail=await executeValidatedRolePlan(input(plan([{id:'dev',role:'dev',dependsOn:[],evidencePhase:'B1',contextBudgetTokens:20,timeoutMs:100}]),async r=>({status:'handoff',handoff:handoff(r)}),{merger:{merge:async()=> 'plausible but wrong'}}));assert.equal(gateFail.reason,'final-gate-rejected'); });
 console.log(`\n${passed} passed, ${failed} failed`); process.exit(failed?1:0);
} main();
